import { Metadata } from 'next';
import { Suspense } from 'react';
import { Container } from '../../shered/components/shared/container';
import Header from '../../shered/components/shared/header';

export const metadata: Metadata = {
  title: 'Green Bite | Корзина',
  description: 'Generated by create next app',
};

export default function CheckoutLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="min-h-screen bg-main">
      <Suspense>
        <Header hasSearch={false} />
      </Suspense>
      <Container>{children}</Container>
    </main>
  );
}
